name: VPS Setup & Deployment

on:
  push:
    branches: [main]
    paths: ['docker-compose.nginx.yml','.github/workflows/pipeline.yml','vps_setup.sh']

jobs:
  server-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Transfer setup files
        run: |
          pwd
          sshpass -p "${{ secrets.ROOT_PASSWORD }}" scp -o StrictHostKeyChecking=no \
            ${{ github.workspace }}/vps_setup.sh \
            root@${{ secrets.VPS_IP }}:~/

      - name: Execute setup
        run: |
          sshpass -p "${{ secrets.ROOT_PASSWORD }}" ssh root@${{ secrets.VPS_IP }} \
            "chmod +x vps_setup.sh && ./vps_setup.sh"

  deploy-nginx:
    runs-on: ubuntu-latest
    needs: server-setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy compose file
        run: |
          sshpass -p "${{ secrets.ROOT_PASSWORD }}" scp -o StrictHostKeyChecking=no \
            docker-compose.nginx.yml root@${{ secrets.VPS_IP }}:/root/

      - name: Launch service
        run: |
          sshpass -p "${{ secrets.ROOT_PASSWORD }}" ssh root@${{ secrets.VPS_IP }} \
            "docker compose -f /root/docker-compose.nginx.yml up -d"